spring:
  application:
    name: gc-pacientes
  datasource:
    url: jdbc:postgresql://localhost:5432/pacientes
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  ai:
    mcp:
      server:
        name: gc-pacientes
        version: 1.0.0
        protocol: streamable
        stdio: false
        type: sync
        streamable-http:
          mcp-endpoint: /api/mcp
          keep-alive-interval: 30s

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}